ktor {
    deployment {
        port = 8081
        host = "0.0.0.0"
    }
}

abc {
    jwtSecret = "change-me-in-production"
    jwtIssuer = "abc-cash"
    jwtAudience = "abc-cash-app"
    jwtRealm = "ABC Cash API"
}

database {
    url = "jdbc:postgresql://localhost:5432/abc_cash"
    user = "abc_cash"
    password = "change-me"
    driver = "org.postgresql.Driver"
}
